[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_extra_dirs =
  ../lib
build_flags =
  -D CORE_DEBUG_LEVEL=2
  -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  olikraus/U8g2@^2.36.1
  jgromes/RadioLib@^6.5.0
  fastled/FastLED@^3.6.0
