[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs =
  ../lib
build_flags =
  -D CORE_DEBUG_LEVEL=2
lib_deps =
  jgromes/RadioLib@^6.5.0
  fastled/FastLED@^3.6.0
